### ISSUE TITLE
Match by position

### ISSUE THREAD

**Issue by loretoparisi** [yuku-t/textoverlay#19]
Is it possibile to match a word or more words by character begin and end positions?
In my understanding I should extend the `Strategy` interface

```typescript
export interface Strategy {
  match: Matcher;
  css: CssStyle;
}
``` 

and implement a new `Matcher` interface

```typescript
export interface Matcher {
  lastIndex: number;
  exec: (input: string) => null | [string] | RegExpExecArray;
}
```

but not rule based but positional, having as input `charOffsetBegin` and `charOffsetEnd` positioanl values and - of course - I should pass the current `node` begin and end offsets in `computeOverlayNodes`

```typescript
private computeOverlayNodes(): Node[] {
    return this.strategies.reduce((ns: Node[], strategy) => {
      const highlight = document.createElement('span');
      setStyle(highlight, strategy.css);
      return Array.prototype.concat.apply([], ns.map((node) => {
        if (node.nodeType !== Node.TEXT_NODE) {
          return node;
        }
        const text = node.textContent || '';
        const resp = [];
        while (true) {
          const prevIndex = strategy.match.lastIndex;
          const match = strategy.match.exec(text);
          if (!match) {
            resp.push(document.createTextNode(text.slice(prevIndex)));
            break;
          }
          const str = match[0];
          resp.push(document.createTextNode(
              text.slice(prevIndex, strategy.match.lastIndex - str.length)));
          const span = highlight.cloneNode();
          span.textContent = str;
          resp.push(span);
        }
        return resp;
      }));
    }, [document.createTextNode(this.textarea.value)]);
  }
```

All suggestions are welcome!

**Comment by loretoparisi** [comment]
**[UPDATE]**

I came out within the `computeOverlayNodes` to get the char begin and end like

```typescript
const charBegin = (strategy.match.lastIndex - str.length);
const charEnd = strategy.match.lastIndex;
```

The problem is that I'm getting this info from the `match` function, while in my case I should need this _before a match_ supposed that I'm passing as input something like

```json
{
   "text": "hello",
   "charBegin": 0,
   "charEnd": 4
}

**Comment by glebm** [comment]
As I understand, you want to style a substring at the given indices?

For that, you can pass a Matcher that sets its `lastIndex` to the start index you want and returns the `[substring]` from the start index until the end index.

**Comment by loretoparisi** [comment]
@glebm thanks, yes basically I have as input the whole text splitted by tokens this means that I already have for each word I have to match:

```javascript
[
{
   "text": "hello",
   "charBegin": 0,
   "charEnd": 4
},
{
   "text": "how",
   "charBegin": 6,
   "charEnd": 8
} ,
{
   "text": "are",
   "charBegin": 9,
   "charEnd": 11
}
]
```

etc.

While the `computeOverlayNodes` is working on a single node, I should match by position that word and then applying the style as with the `Matcher` interface, so that I would call it like

```typescript
// first approach by char end, start
new Textoverlay(textarea, [
        {
            match: [0,4],
            css: { 'background-color': '#d8dfea' },
        },
        {
            match: [6,8],
            css: { 'background-color': '#cc9393' },
        },
        {
            match: [9,11],
            css: { 'background-color': '#ddd' },
        }
    ]);
```

the clue now is how to apply this since I actually have the text as input, so I was trying like

```typescript
// second approach by consecutive word matching
new Textoverlay(textarea, [
        {
            match: /You/,
            css: { 'background-color': '#d8dfea' },
        },
        {
            match: /probably/,
            css: { 'background-color': '#cc9393' },
        },
        {
            match: /think/,
            css: { 'background-color': '#ddd' },
        }
    ]);
```

so that to have the match for each word directly (since I have for each tuple (word,start,end), but the `computeOverlayNodes` with this setup seems to create an infinite loop...

**Comment by glebm** [comment]
Here is a working example using unmodified textoverlay v0.3.0:

https://codepen.io/glebm/pen/QxEbey?editors=0010

> seems to create an infinite loop...

Regexes *must* have the `g` flag

**Comment by loretoparisi** [comment]
@glebm awesome! 💯 🥇 thank you!
