### ISSUE TITLE
Integration with React components

### ISSUE THREAD

**Issue by loretoparisi** [yuku-t/textoverlay#20]
I have successfully used TextOverlay with standard jQuery DOM HTML5 applications (thank you for your help with the _RangeMatcher_ 👍 )

While using React applications, it is not possibile to modify DOM elements due to React `render` protection - see [here](https://stackoverflow.com/questions/36825895/chrome-extension-mutating-running-react-application?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).
Now according to React doc [Integrating with Other Libraries](https://reactjs.org/docs/integrating-with-other-libraries.html) it is possibile to build a extension component to interact with react web app.
I'm not sure if this is the right way anyways, any suggestion?

**Note.**
Other approaches like React Code injections, simply does not work like https://gist.github.com/loretoparisi/a5cd7ab92d221578cc540f530a777b56

**Comment by loretoparisi** [comment]
**[UPDATE]**
My last attempt was using development tree **React** and **ReactDOM** client libraries, this work and I can inject the libs and push a new React component some where like:

```javascript
let injc=(src,cbk) => { let script = document.createElement('script');script.src = src;document.getElementsByTagName('head')[0].appendChild(script);script.onload=()=>cbk() }
injc("https://unpkg.com/react@16/umd/react.development.js",() => injc("https://unpkg.com/react-dom@16/umd/react-dom.development.js",() => { console.log("Hello")}))
ReactDOM.render('<Hello name="World" />', document.getElementById('container'));
```

so I can inject the libraries, and when ready I execute my **ReactDOM.render** method to change the React app contents successfully.
May this can be used in the TextOverlay, as last stage to modify the contents.
So as soon as I have modified the text nodes in `computeOverlayNodes` I should do something like 

```javascript
ReactDOM.render(contents, textarea)
```

so used in the rendering method `updateOverlayNodes` like:

```typescript
this.computeOverlayNodes().forEach((node) => {
   ReactDOM.render(node, this.overlay)
   //this.overlay.appendChild(node);
});
```

just to have an idea, this actually causes an error since the first param it is not what **ReacDOM** JSX expects...

**Comment by loretoparisi** [comment]
So I came up with this solution so far

```typescript
this.computeOverlayNodes().forEach((node) => {
    var reactObj=HTMLReactParser(node.outerHTML);
     ReactDOM.render(reactObj, this.textarea);
     //this.overlay.appendChild(node);
}); 
```

where `HTMLReactParser` translates a HTML element to a `ReactElement` directly from this api [here](https://github.com/remarkablemark/html-react-parser/issues)

It works good _visually_, even if I'm not sure I'm attaching the overlay in the right place.

**Comment by glebm** [comment]
This seems like a question better suited for StackOverflow than the library's issue tracker.

**Comment by loretoparisi** [comment]
@glebm ok thank you, I have posted a question to SF with an example [here](https://stackoverflow.com/questions/50813685/modify-react-app-in-chrome-extension).
